/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Diego
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        addPanelsToConsumerInfo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_background = new javax.swing.JPanel();
        lbl_numConsumers = new javax.swing.JLabel();
        lbl_numProducers = new javax.swing.JLabel();
        btn_addProducer = new javax.swing.JButton();
        btn_addConsumer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnl_consumerInfo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1040, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(775, 579));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_background.setBackground(new java.awt.Color(255, 204, 255));
        pnl_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_numConsumers.setText("No: 5");
        pnl_background.add(lbl_numConsumers, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        lbl_numProducers.setText("No: 5");
        pnl_background.add(lbl_numProducers, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, -1, 20));

        btn_addProducer.setText("Add Producer");
        btn_addProducer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addProducerActionPerformed(evt);
            }
        });
        pnl_background.add(btn_addProducer, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 130, 50));

        btn_addConsumer.setText("Add Consumer");
        btn_addConsumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addConsumerActionPerformed(evt);
            }
        });
        pnl_background.add(btn_addConsumer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 140, 50));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new Dimension(250, pnl_consumerInfo.getPreferredSize().height));
        jScrollPane1.setViewportView(pnl_consumerInfo);

        pnl_consumerInfo.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(pnl_consumerInfo);

        pnl_background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 250, 460));

        getContentPane().add(pnl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addConsumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addConsumerActionPerformed

    
    }//GEN-LAST:event_btn_addConsumerActionPerformed

    private void btn_addProducerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addProducerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addProducerActionPerformed
    
    private void addPanelsToConsumerInfo() {
        for (int i = 1; i <= 30; i++) {
            JPanel jPanel = new JPanel();
            jPanel.add(new JLabel("Label " + i));
            pnl_consumerInfo.add(jPanel);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addConsumer;
    private javax.swing.JButton btn_addProducer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_numConsumers;
    private javax.swing.JLabel lbl_numProducers;
    private javax.swing.JPanel pnl_background;
    private javax.swing.JPanel pnl_consumerInfo;
    // End of variables declaration//GEN-END:variables
}
