/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Diego
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        addPanelsToConsumerInfo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_background = new javax.swing.JPanel();
        lbl_numConsumers = new javax.swing.JLabel();
        lbl_numProducers = new javax.swing.JLabel();
        btn_addConsumer = new javax.swing.JButton();
        pnl_producerInfo = new javax.swing.JScrollPane();
        pnl_consumerInfo1 = new javax.swing.JPanel();
        img_restaurant = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnl_consumerInfo = new javax.swing.JPanel();
        btn_addProducer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1126, 617));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_background.setBackground(new java.awt.Color(51, 0, 0));
        pnl_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_numConsumers.setFont(new java.awt.Font("Cascadia Code", 0, 20)); // NOI18N
        lbl_numConsumers.setForeground(new java.awt.Color(239, 221, 221));
        lbl_numConsumers.setText("Consumers: 5");
        pnl_background.add(lbl_numConsumers, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        lbl_numProducers.setFont(new java.awt.Font("Cascadia Mono", 0, 20)); // NOI18N
        lbl_numProducers.setForeground(new java.awt.Color(239, 221, 221));
        lbl_numProducers.setText("Producers: 5");
        pnl_background.add(lbl_numProducers, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, -1, 20));

        btn_addConsumer.setBackground(new java.awt.Color(0, 0, 0));
        btn_addConsumer.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btn_addConsumer.setForeground(new java.awt.Color(255, 255, 255));
        btn_addConsumer.setText("Add Consumer");
        btn_addConsumer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        btn_addConsumer.setFocusPainted(false);
        btn_addConsumer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addConsumerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addConsumerMouseExited(evt);
            }
        });
        pnl_background.add(btn_addConsumer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 230, 50));

        pnl_producerInfo.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        pnl_producerInfo.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        pnl_producerInfo.setPreferredSize(new Dimension(250, pnl_consumerInfo.getPreferredSize().height));
        pnl_producerInfo.setViewportView(pnl_consumerInfo);

        pnl_consumerInfo1.setLayout(new java.awt.GridLayout(0, 1));
        pnl_producerInfo.setViewportView(pnl_consumerInfo1);

        pnl_background.add(pnl_producerInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, 210, 470));

        img_restaurant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background.png"))); // NOI18N
        img_restaurant.setRequestFocusEnabled(false);
        pnl_background.add(img_restaurant, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 610, 460));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new Dimension(250, pnl_consumerInfo.getPreferredSize().height));
        jScrollPane1.setViewportView(pnl_consumerInfo);

        pnl_consumerInfo.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(pnl_consumerInfo);

        pnl_background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 210, 470));

        btn_addProducer.setBackground(new java.awt.Color(0, 0, 0));
        btn_addProducer.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        btn_addProducer.setForeground(new java.awt.Color(255, 255, 255));
        btn_addProducer.setText("Add Producer");
        btn_addProducer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        btn_addProducer.setFocusPainted(false);
        btn_addProducer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addProducerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addProducerMouseExited(evt);
            }
        });
        btn_addProducer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addProducerActionPerformed(evt);
            }
        });
        pnl_background.add(btn_addProducer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 230, 50));

        getContentPane().add(pnl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addConsumerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addConsumerMouseEntered
        btn_addConsumer.setBackground(new Color(21,21,21));
        btn_addConsumer.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_addConsumerMouseEntered

    private void btn_addConsumerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addConsumerMouseExited
       btn_addConsumer.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btn_addConsumerMouseExited

    private void btn_addProducerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addProducerMouseEntered
        btn_addProducer.setBackground(new Color(21,21,21));
        btn_addProducer.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_addProducerMouseEntered

    private void btn_addProducerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addProducerMouseExited
        btn_addProducer.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_btn_addProducerMouseExited

    private void btn_addProducerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addProducerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addProducerActionPerformed
    
    private void addPanelsToConsumerInfo() {
        for (int i = 1; i <= 30; i++) {
            JPanel jPanel = new JPanel();
            jPanel.add(new JLabel("Label " + i));
            pnl_consumerInfo.add(jPanel);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addConsumer;
    private javax.swing.JButton btn_addProducer;
    private javax.swing.JLabel img_restaurant;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_numConsumers;
    private javax.swing.JLabel lbl_numProducers;
    private javax.swing.JPanel pnl_background;
    private javax.swing.JPanel pnl_consumerInfo;
    private javax.swing.JPanel pnl_consumerInfo1;
    private javax.swing.JScrollPane pnl_producerInfo;
    // End of variables declaration//GEN-END:variables
}
